import type {
  BatchLogEntry,
  ErrorLogEntry,
  Partner,
  PresetQuery,
} from "./types"

/**
 * SFR-021 목업 데이터.
 * 실제 기간계 API를 대체하는 정적 샘플. 모든 수치·명칭은 데모 목적의 가상값.
 */

export const mockPartners: Partner[] = [
  {
    id: "p-001",
    name: "제논라이프 서울 고객플라자",
    shortName: "제논라이프 서울",
    region: "서울",
    institutionType: "협회",
    programs: ["개인회생", "새출발기금", "사전채무조정"],
    address: "서울특별시 중구 세종대로 39",
    phone: "02-6362-2000",
    department: "채무조정상담부",
    metaScore: 0.94,
    vectorScore: 0.91,
  },
  {
    id: "p-002",
    name: "제논라이프 경기남부 고객플라자",
    shortName: "제논라이프 경기남부",
    region: "경기",
    institutionType: "협회",
    programs: ["개인회생", "사전채무조정", "신용교육"],
    address: "경기도 수원시 팔달구 인계로 178",
    phone: "031-259-6300",
    department: "상담지원과",
    metaScore: 0.9,
    vectorScore: 0.88,
  },
  {
    id: "p-003",
    name: "한국주택금융공사",
    shortName: "주금공",
    region: "서울",
    institutionType: "공사",
    programs: ["소액대출", "새출발기금"],
    address: "서울특별시 중구 소공로 94",
    phone: "02-2014-8114",
    department: "서민금융지원부",
    metaScore: 0.86,
    vectorScore: 0.82,
  },
  {
    id: "p-004",
    name: "수원신용협동조합",
    region: "경기",
    institutionType: "신협",
    programs: ["소액대출", "신용교육"],
    address: "경기도 수원시 영통구 광교로 145",
    phone: "031-217-4455",
    department: "대출상담팀",
    metaScore: 0.88,
    vectorScore: 0.85,
  },
  {
    id: "p-005",
    name: "인천서민금융통합지원센터",
    shortName: "인천 서금센터",
    region: "인천",
    institutionType: "협회",
    programs: ["개인회생", "새출발기금", "소액대출"],
    address: "인천광역시 남동구 정각로 29",
    phone: "032-440-3100",
    department: "통합상담센터",
    metaScore: 0.89,
    vectorScore: 0.86,
  },
  {
    id: "p-006",
    name: "부산은행 사회공헌단",
    region: "부산",
    institutionType: "은행",
    programs: ["신용교육", "소액대출"],
    address: "부산광역시 남구 문현금융로 30",
    phone: "051-620-3000",
    department: "사회공헌부",
    metaScore: 0.83,
    vectorScore: 0.79,
  },
  {
    id: "p-007",
    name: "대구사회복지공동모금회",
    region: "대구",
    institutionType: "사회복지기관",
    programs: ["신용교육"],
    address: "대구광역시 중구 국채보상로 586",
    phone: "053-667-9981",
    department: "복지사업팀",
    metaScore: 0.8,
    vectorScore: 0.77,
  },
  {
    id: "p-008",
    name: "서민금융진흥원 서울강북센터",
    shortName: "서금원 강북",
    region: "서울",
    institutionType: "협회",
    programs: ["소액대출", "새출발기금", "신용교육"],
    address: "서울특별시 강북구 도봉로 117",
    phone: "02-944-3100",
    department: "서민금융상담부",
    metaScore: 0.92,
    vectorScore: 0.89,
  },
  {
    id: "p-009",
    name: "광주광역시 서민금융지원센터",
    region: "광주",
    institutionType: "사회복지기관",
    programs: ["소액대출", "신용교육"],
    address: "광주광역시 서구 상무중앙로 110",
    phone: "062-613-2100",
    department: "금융지원팀",
    metaScore: 0.78,
    vectorScore: 0.74,
  },
  {
    id: "p-010",
    name: "대전신용보증재단",
    region: "대전",
    institutionType: "공사",
    programs: ["소액대출", "사전채무조정"],
    address: "대전광역시 서구 청사로 136",
    phone: "042-380-3800",
    department: "보증심사부",
    metaScore: 0.81,
    vectorScore: 0.79,
  },
  {
    id: "p-011",
    name: "성남새마을금고 본점",
    region: "경기",
    institutionType: "신협",
    programs: ["소액대출"],
    address: "경기도 성남시 수정구 산성대로 350",
    phone: "031-721-8800",
    department: "여신관리팀",
    metaScore: 0.84,
    vectorScore: 0.81,
  },
  {
    id: "p-012",
    name: "강원도 원주 신용회복상담소",
    shortName: "신복위 원주",
    region: "강원",
    institutionType: "협회",
    programs: ["개인회생", "사전채무조정"],
    address: "강원특별자치도 원주시 단계로 153",
    phone: "033-744-2020",
    department: "채무조정상담과",
    metaScore: 0.76,
    vectorScore: 0.73,
  },
  {
    id: "p-013",
    name: "국민은행 사회가치부",
    region: "서울",
    institutionType: "은행",
    programs: ["신용교육", "소액대출"],
    address: "서울특별시 영등포구 국제금융로8길 26",
    phone: "02-2073-7114",
    department: "사회가치부",
    metaScore: 0.82,
    vectorScore: 0.8,
  },
  {
    id: "p-014",
    name: "한국사회복지협의회",
    region: "서울",
    institutionType: "사회복지기관",
    programs: ["신용교육", "새출발기금"],
    address: "서울특별시 마포구 월드컵북로 402",
    phone: "02-2077-3700",
    department: "복지사업국",
    metaScore: 0.79,
    vectorScore: 0.76,
  },
]

export const partnerById = (id: string): Partner | undefined =>
  mockPartners.find((p) => p.id === id)

export const presetQueries: PresetQuery[] = [
  {
    id: "preset-1",
    query: "개인회생 지원 협약기관 찾아줘",
    extractedFilters: [
      { label: "제도: 개인회생", category: "제도" },
      { label: "기관유형: 협회", category: "기관유형" },
    ],
    resultIds: ["p-001", "p-002", "p-005", "p-012"],
  },
  {
    id: "preset-2",
    query: "소액대출 연계 수도권 기관 알려줘",
    extractedFilters: [
      { label: "지역: 서울·경기·인천", category: "지역" },
      { label: "제도: 소액대출", category: "제도" },
    ],
    resultIds: ["p-003", "p-004", "p-005", "p-008", "p-011"],
  },
  {
    id: "preset-3",
    query: "약칭 '신복위' 유사 기관 검색",
    extractedFilters: [
      { label: "기관유형: 협회", category: "기관유형" },
      { label: "약칭: 신복위", category: "기관유형" },
    ],
    resultIds: ["p-001", "p-002", "p-012"],
    highlightAlias: "신복위",
  },
]

export const batchLogs: BatchLogEntry[] = [
  {
    id: "b-001",
    executedAt: "2026-04-08 09:15",
    totalCount: 10284,
    successCount: 10284,
    failureCount: 0,
    status: "성공",
    duration: "4분 12초",
  },
  {
    id: "b-002",
    executedAt: "2026-04-08 03:00",
    totalCount: 10280,
    successCount: 10278,
    failureCount: 2,
    status: "부분 성공",
    duration: "4분 38초",
  },
  {
    id: "b-003",
    executedAt: "2026-04-07 21:00",
    totalCount: 10276,
    successCount: 10276,
    failureCount: 0,
    status: "성공",
    duration: "3분 58초",
  },
  {
    id: "b-004",
    executedAt: "2026-04-07 15:00",
    totalCount: 10270,
    successCount: 0,
    failureCount: 10270,
    status: "실패",
    duration: "2분 05초",
  },
  {
    id: "b-005",
    executedAt: "2026-04-07 09:00",
    totalCount: 10270,
    successCount: 10270,
    failureCount: 0,
    status: "성공",
    duration: "4분 01초",
  },
]

export const errorLogs: ErrorLogEntry[] = [
  {
    id: "e-001",
    title: "기간계 API 504 Gateway Timeout",
    occurredAt: "2026-04-07 15:02",
    detail: "재시도 3회 실패 · 기간계 연동 게이트웨이 응답 지연",
    kbRetained: true,
    reasonLogged: true,
    adminNotified: true,
  },
  {
    id: "e-002",
    title: "변경분 청킹 실패 (스키마 불일치)",
    occurredAt: "2026-04-08 03:04",
    detail: "신규 컬럼 'branch_code' 미매핑 — 2건 누락, 배치 전체는 계속 진행",
    kbRetained: true,
    reasonLogged: true,
    adminNotified: true,
  },
  {
    id: "e-003",
    title: "벡터 인덱스 일시 잠금",
    occurredAt: "2026-04-05 03:12",
    detail: "인덱스 리빌드 중 쓰기 충돌 — 해당 사이클 skip 후 정상 복구",
    kbRetained: true,
    reasonLogged: true,
    adminNotified: true,
  },
]

export const ingestionSummary = {
  totalPartners: 10284,
  lastSyncAt: "2026-04-08 09:15",
  lastSyncRelative: "약 2시간 전",
  dailyCreated: 32,
  dailyUpdated: 18,
  dailyDeleted: 4,
} as const
